parameters:
  graphql_extensions.classes.file_entity:
  graphql_extensions.classes.path_generator: "Youshido\\GraphQlExtensionsBundle\\Services\\PathGenerator\\DatePathGenerator"
  graphql_extensions.classes.path_resolver: "Youshido\\GraphQlExtensionsBundle\\Services\\PathResolver\\LocalPathResolver"


services:
  graphql_extensions.resolver.base:
    abstract: true
    class: Youshido\GraphQlExtensionsBundle\Resolver\AbstractResolver
    calls:
      - [ setInitialDependencies, ["@security.token_storage"] ]

  graphql_extensions.path_generator:
      public: false
      class: "%graphql_extensions.classes.path_generator%"

  graphql_extensions.locator:
      class: "Youshido\\GraphQlExtensionsBundle\\Services\\Locator\\Locator"
      arguments:
        - "@graphql_extensions.path_generator"
        - "@graphql_extensions.path_resolver"
        - "%graphql_extensions.storage%"

  graphql_extensions.path_resolver:
      public: false
      class: "%graphql_extensions.classes.path_resolver%"
      arguments:
          - "@router"
          - "%graphql_extensions.config.web_root%"
          - "%graphql_extensions.config.path_prefix%"
          - "%graphql_extensions.config.host%"
          - "%graphql_extensions.config.scheme%"